# Generated by Django 6.1 on 2026-08-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_clubes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membresia",
            name="rol",
            field=models.CharField(
                choices=[
                    ("presidente", "Presidente"),
                    ("vicepresidente", "Vicepresidente"),
                    ("secretario", "Secretario"),
                    ("coor_eventos", "Coordinador de Eventos"),
                    ("coor_rsocial", "Coordinador de Redes Sociales"),
                    ("miembro", "Miembro"),
                    ("aspirante", "Aspirante"),
                ],
                default="aspirante",
                max_length=30,
            ),
        ),
    ]
