# Generated by Django 6.1 on 2026-08-11 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_clubes', '0002_alter_membresia_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asamblea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_cierre', models.DateTimeField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asambleas', to='api_clubes.club')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado')], default='Disponible', max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='api_clubes.club')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lista', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('asamblea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='api_clubes.asamblea')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('asamblea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='api_clubes.asamblea')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_clubes.opcionvoto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('asamblea', 'usuario')},
            },
        ),
    ]
